# Generated by Django 4.1 on 2022-08-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='retailer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=55, null=True, unique=True)),
                ('eco_num', models.CharField(max_length=12, unique=True, verbose_name=' کد اقتصادی ')),
                ('post_code', models.CharField(default='', max_length=10, verbose_name=' کد پستی ')),
                ('full_add', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name=' آدرس کامل ')),
                ('manager_name', models.CharField(blank=True, default='', max_length=30, verbose_name='نام مدیر')),
                ('manager_phone', models.CharField(default='', max_length=20, verbose_name=' شماره مدیر')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='accounts.city', verbose_name='شهر')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='accounts.region', verbose_name='منطقه')),
            ],
        ),
    ]
