# Generated by Django 4.1 on 2022-08-13 10:27

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=30, unique=True, verbose_name='نام کاربری')),
                ('date_joined', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vendor', models.BooleanField(default=False, verbose_name='نماینده توزیع')),
                ('is_retailer', models.BooleanField(default=False, verbose_name='فروشگاه')),
                ('profile_image', models.ImageField(blank=True, default=accounts.models.get_default_profile_image, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name=' شماره تماس ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='کد شهر')),
                ('name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='نام شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='کد منطقه')),
                ('name', models.CharField(blank=True, default='', max_length=60, verbose_name='نام منطقه')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='accounts.city', verbose_name='شهر')),
            ],
        ),
    ]
