# Generated by Django 4.1 on 2022-08-13 18:49

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
        ('vendor', '0003_vendor_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('paid_amount', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='مبلغ قابل پرداخت')),
                ('total_number', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='تعداد کالا')),
                ('seller_confirmation', models.BooleanField(default=False, verbose_name='تایید نماینده')),
                ('buyer_confirmation', models.BooleanField(default=False, verbose_name='تایید فروشگاه')),
                ('cash_settlement', models.BooleanField(default=False, verbose_name='پرداخت هنگام تحوبل')),
                ('draft_settlement', models.BooleanField(default=False, verbose_name='پرداخت چک')),
                ('trust_settlement', models.BooleanField(default=False, verbose_name='پرداخت اعتباری')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='retailer.retailer', verbose_name='خریدار')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendor.vendor', verbose_name='فروشنده')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('discount_percent', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='vendor.vendorproduct')),
            ],
        ),
    ]
